# Sensors Table

In [1]:
import pandas as pd
import numpy as np

In [2]:
a = pd.read_csv('./data/prepared/air.csv')
b = pd.read_csv('./data/prepared/noise.csv')
c = pd.read_csv('./data/prepared/water.csv')
d = pd.read_csv('./data/prepared/weather.csv')

In [3]:
a.head()

,date,sensor_id,vendor,sensor_model,latitude,longitude,zone,micron_1,micron_2,micron_10,sulfur,ozone,carbon,nitrogen,alert_triggered,sensor_status
0,2021-05-20 00:01:27,689324d0f345350d,ATT,AQM-01-00-01-00-01-00-GY,29.34473,-98.435672,Brooks,6,6,7,0,0.0,0,0,None,Normal
1,2021-05-20 00:04:27,689324d0f345350d,ATT,AQM-01-00-01-00-01-00-GY,29.34473,-98.435672,Brooks,6,6,7,0,0.0,0,0,None,Normal
2,2021-05-20 00:07:28,689324d0f345350d,ATT,AQM-01-00-01-00-01-00-GY,29.34473,-98.435672,Brooks,6,6,7,0,0.0,0,0,None,Normal
3,2021-05-20 00:10:27,689324d0f345350d,ATT,AQM-01-00-01-00-01-00-GY,29.34473,-98.435672,Brooks,6,6,7,0,0.0,0,0,None,Normal
4,2021-05-20 00:13:27,689324d0f345350d,ATT,AQM-01-00-01-00-01-00-GY,29.34473,-98.435672,Brooks,6,6,7,0,0.0,0,0,None,Normal

In [4]:
b.head()

,date,sensor_id,vendor,sensor_model,latitude,longitude,zone,noise_level,alert_triggered,sensor_status
0,2021-05-20 00:01:27,689324d0f345350d,ATT,AQM-01-00-01-00-01-00-GY,29.34473,-98.435672,Brooks,59,No,Normal
1,2021-05-20 00:04:27,689324d0f345350d,ATT,AQM-01-00-01-00-01-00-GY,29.34473,-98.435672,Brooks,59,No,Normal
2,2021-05-20 00:07:28,689324d0f345350d,ATT,AQM-01-00-01-00-01-00-GY,29.34473,-98.435672,Brooks,59,No,Normal
3,2021-05-20 00:10:27,689324d0f345350d,ATT,AQM-01-00-01-00-01-00-GY,29.34473,-98.435672,Brooks,59,No,Normal
4,2021-05-20 00:13:27,689324d0f345350d,ATT,AQM-01-00-01-00-01-00-GY,29.34473,-98.435672,Brooks,59,No,Normal

In [5]:
c.head()

,date,sensor_id,vendor,sensor_model,latitude,longitude,zone,temp_f,dist_to_water_ft,dist_to_floor_ft,alert_triggered,sensor_status,water_level
0,2021-06-01 00:02:55,400791,ATT,ranger sensor,29.345167,-98.451583,Brooks,-999,14.370079,15.833333,No,Normal,1.463255
1,2021-06-01 00:07:55,400791,ATT,ranger sensor,29.345167,-98.451583,Brooks,-999,14.370079,15.833333,No,Normal,1.463255
2,2021-06-01 00:12:55,400791,ATT,ranger sensor,29.345167,-98.451583,Brooks,-999,14.402887,15.833333,No,Normal,1.430446
3,2021-06-01 00:17:55,400791,ATT,ranger sensor,29.345167,-98.451583,Brooks,-999,14.370079,15.833333,No,Normal,1.463255
4,2021-06-01 00:22:55,400791,ATT,ranger sensor,29.345167,-98.451583,Brooks,-999,14.402887,15.833333,No,Normal,1.430446

In [6]:
d.head()

,date,sensor_id,vendor,sensor_model,latitude,longitude,zone,temp_f,humidity,dewpoint_f,pressure_pa,alert_triggered,sensor_status
0,2021-04-20 00:04:46,689324d0f345350d,ATT,AQM-01-00-01-00-01-00-GY,29.34473,-98.435672,Brooks,64.0,45.0,42.584509,992,NaN,Normal
1,2021-04-20 00:14:47,689324d0f345350d,ATT,AQM-01-00-01-00-01-00-GY,29.34473,-98.435672,Brooks,64.0,45.0,42.584509,992,NaN,Normal
2,2021-04-20 00:24:47,689324d0f345350d,ATT,AQM-01-00-01-00-01-00-GY,29.34473,-98.435672,Brooks,64.0,45.0,42.584509,992,NaN,Normal
3,2021-04-20 00:34:46,689324d0f345350d,ATT,AQM-01-00-01-00-01-00-GY,29.34473,-98.435672,Brooks,64.0,45.0,42.584509,992,NaN,Normal
4,2021-04-20 00:44:46,689324d0f345350d,ATT,AQM-01-00-01-00-01-00-GY,29.34473,-98.435672,Brooks,64.0,45.0,42.584509,992,NaN,Normal

In [7]:
a['sensor_type'] = 'air'
b['sensor_type'] = 'noise'
c['sensor_type'] = 'water'
d['sensor_type'] = 'weather'

In [8]:
air_sensors = a.groupby(['zone', 'sensor_id', 'sensor_type',
                         'vendor', 'latitude', 'longitude']).count().reset_index().iloc[:, :6]

In [9]:
noise_sensors = b.groupby(['zone', 'sensor_id', 'sensor_type',
                           'vendor', 'latitude', 'longitude']).count().reset_index().iloc[:, :6]

In [10]:
water_sensors = c.groupby(['zone', 'sensor_id', 'sensor_type',
                           'vendor', 'latitude', 'longitude']).count().reset_index().iloc[:, :6]

In [11]:
weather_sensors = d.groupby(['zone', 'sensor_id', 'sensor_type',
                             'vendor', 'latitude', 'longitude']).count().reset_index().iloc[:, :6]

In [12]:
merge_1 = pd.concat([air_sensors, noise_sensors, water_sensors, weather_sensors],
                    ignore_index=True)

In [13]:
merge_1

              zone         sensor_id sensor_type vendor   latitude  longitude
0           Brooks  63d684c940ce1f6b         air    ATT  29.345660 -98.434544
1           Brooks  689324d0f345350d         air    ATT  29.344730 -98.435672
2           Brooks  6de2cc6034fd26e8         air    ATT  29.344120 -98.436440
3           Brooks             70449         air  ITRON  29.346020 -98.439550
4         Downtown  63db58629a2d20a7         air    ATT  29.416610 -98.484080
5         Downtown  64d7e0e4cfeba0b6         air    ATT  29.414910 -98.481400
6         Downtown  64d7e4dbde37ccb5         air    ATT  29.415910 -98.482880
7         Downtown             70456         air  ITRON  29.424570 -98.494570
8   Medical Center  63e0b0eae3495a39         air    ATT  29.510070 -98.580288
9   Medical Center  6dee283d397b9803         air    ATT  29.507520 -98.581368
10  Medical Center             70463         air  ITRON  29.504840 -98.583500
11  Medical Center  7b48389537e7a6c7         air    ATT  29.507900 -98.581280
12          Brooks             63554       noise  ITRON  29.341590 -98.439560
13          Brooks  63d684c940ce1f6b       noise    ATT  29.345660 -98.434544
14          Brooks  689324d0f345350d       noise    ATT  29.344730 -98.435672
15          Brooks  6de2cc6034fd26e8       noise    ATT  29.344120 -98.436440
16        Downtown             63540       noise  ITRON  29.422880 -98.486930
17        Downtown             63547       noise  ITRON  29.422100 -98.483660
18        Downtown  63db58629a2d20a7       noise    ATT  29.416610 -98.484080
19        Downtown  64d7e0e4cfeba0b6       noise    ATT  29.414860 -98.481488
20        Downtown  64d7e4dbde37ccb5       noise    ATT  29.415910 -98.482880
21  Medical Center             63568       noise  ITRON  29.509300 -98.583610
22  Medical Center  63e0b0eae3495a39       noise    ATT  29.510070 -98.580288
23  Medical Center  6dee283d397b9803       noise    ATT  29.507520 -98.581368
24  Medical Center  7b48389537e7a6c7       noise    ATT  29.507900 -98.581280
25          Brooks             61433       water  ITRON  29.344070 -98.452230
26          Brooks            400791       water    ATT  29.345167 -98.451583
27        Downtown             61440       water  ITRON  29.421890 -98.485190
28        Downtown            400783       water    ATT  29.421882 -98.485166
29  Medical Center             61447       water  ITRON  29.510960 -98.586040
30  Medical Center            400789       water    ATT  29.511164 -98.586094
31          Brooks  63d684c940ce1f6b     weather    ATT  29.345660 -98.434544
32          Brooks  689324d0f345350d     weather    ATT  29.344730 -98.435672
33          Brooks  6de2cc6034fd26e8     weather    ATT  29.344120 -98.436440
34          Brooks             70449     weather  ITRON  29.346020 -98.439550
35        Downtown  63db58629a2d20a7     weather    ATT  29.416610 -98.484080
36        Downtown  64d7e0e4cfeba0b6     weather    ATT  29.414910 -98.481400
37        Downtown  64d7e4dbde37ccb5     weather    ATT  29.415910 -98.482880
38        Downtown             70456     weather  ITRON  29.424570 -98.494570
39  Medical Center  63e0b0eae3495a39     weather    ATT  29.510070 -98.580288
40  Medical Center  6dee283d397b9803     weather    ATT  29.507520 -98.581368
41  Medical Center             70463     weather  ITRON  29.504840 -98.583500
42  Medical Center  7b48389537e7a6c7     weather    ATT  29.507900 -98.581280

In [14]:
sensor_table = merge_1.groupby(['zone', 'sensor_id', 'sensor_type',
                             'vendor', 'latitude', 'longitude']).count().reset_index()

sensor_table

              zone         sensor_id sensor_type vendor   latitude  longitude
0           Brooks             61433       water  ITRON  29.344070 -98.452230
1           Brooks            400791       water    ATT  29.345167 -98.451583
2           Brooks             63554       noise  ITRON  29.341590 -98.439560
3           Brooks  63d684c940ce1f6b         air    ATT  29.345660 -98.434544
4           Brooks  63d684c940ce1f6b       noise    ATT  29.345660 -98.434544
5           Brooks  63d684c940ce1f6b     weather    ATT  29.345660 -98.434544
6           Brooks  689324d0f345350d         air    ATT  29.344730 -98.435672
7           Brooks  689324d0f345350d       noise    ATT  29.344730 -98.435672
8           Brooks  689324d0f345350d     weather    ATT  29.344730 -98.435672
9           Brooks  6de2cc6034fd26e8         air    ATT  29.344120 -98.436440
10          Brooks  6de2cc6034fd26e8       noise    ATT  29.344120 -98.436440
11          Brooks  6de2cc6034fd26e8     weather    ATT  29.344120 -98.436440
12          Brooks             70449         air  ITRON  29.346020 -98.439550
13          Brooks             70449     weather  ITRON  29.346020 -98.439550
14        Downtown             61440       water  ITRON  29.421890 -98.485190
15        Downtown            400783       water    ATT  29.421882 -98.485166
16        Downtown             63540       noise  ITRON  29.422880 -98.486930
17        Downtown             63547       noise  ITRON  29.422100 -98.483660
18        Downtown  63db58629a2d20a7         air    ATT  29.416610 -98.484080
19        Downtown  63db58629a2d20a7       noise    ATT  29.416610 -98.484080
20        Downtown  63db58629a2d20a7     weather    ATT  29.416610 -98.484080
21        Downtown  64d7e0e4cfeba0b6         air    ATT  29.414910 -98.481400
22        Downtown  64d7e0e4cfeba0b6       noise    ATT  29.414860 -98.481488
23        Downtown  64d7e0e4cfeba0b6     weather    ATT  29.414910 -98.481400
24        Downtown  64d7e4dbde37ccb5         air    ATT  29.415910 -98.482880
25        Downtown  64d7e4dbde37ccb5       noise    ATT  29.415910 -98.482880
26        Downtown  64d7e4dbde37ccb5     weather    ATT  29.415910 -98.482880
27        Downtown             70456         air  ITRON  29.424570 -98.494570
28        Downtown             70456     weather  ITRON  29.424570 -98.494570
29  Medical Center             61447       water  ITRON  29.510960 -98.586040
30  Medical Center            400789       water    ATT  29.511164 -98.586094
31  Medical Center             63568       noise  ITRON  29.509300 -98.583610
32  Medical Center  63e0b0eae3495a39         air    ATT  29.510070 -98.580288
33  Medical Center  63e0b0eae3495a39       noise    ATT  29.510070 -98.580288
34  Medical Center  63e0b0eae3495a39     weather    ATT  29.510070 -98.580288
35  Medical Center  6dee283d397b9803         air    ATT  29.507520 -98.581368
36  Medical Center  6dee283d397b9803       noise    ATT  29.507520 -98.581368
37  Medical Center  6dee283d397b9803     weather    ATT  29.507520 -98.581368
38  Medical Center             70463         air  ITRON  29.504840 -98.583500
39  Medical Center             70463     weather  ITRON  29.504840 -98.583500
40  Medical Center  7b48389537e7a6c7         air    ATT  29.507900 -98.581280
41  Medical Center  7b48389537e7a6c7       noise    ATT  29.507900 -98.581280
42  Medical Center  7b48389537e7a6c7     weather    ATT  29.507900 -98.581280

In [15]:
sensor_table.to_csv('./data/prepared/sensor_table.csv', index=False)